name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.8", "3.8", "3.8", "3.8"]
        include:
          - python-version: "3.8"
            toxenv: flake8
          - python-version: "3.8"
            toxenv: isort
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-gh-actions coveralls
      - name: Run tests
        run: tox
      - name: Upload coverage to Coveralls
        if: success() && matrix.python-version == '3.8' && matrix.toxenv == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
