name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flake8 gettext gir1.2-gtk-3.0 python3-gi python3-pytest xvfb

      - name: Run flake8
        run: flake8 .

      - name: Run tests
        run: xvfb-run py.test-3 nfoview

      - name: Install package
        run: python3 setup.py install --prefix=/tmp/local

      - name: Install package with root
        run: python3 setup.py install --root=/tmp/pkg

      - name: Clean up
        run: python3 setup.py clean
