name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt install python3-pip
          sudo pip3 install -r requirements.txt
          sudo pip3 install tox

      - name: Run tests
        run: tox
