name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.8", "3.8", "3.8", "pypy-3.6"]
        django-version: ["2.2", "3.0", "3.1", "main"]
        exclude:
          - python-version: "3.8"
            django-version: "3.0"
          - python-version: "3.8"
            django-version: "3.1"
          - python-version: "3.8"
            django-version: "main"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-gh-actions

      - name: Run tests
        env:
          TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version }}
        run: tox

  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

