name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8

  dockerfile_lint:
    runs-on: ubuntu-22.04
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint:v1.19.0-45-gef91156-alpine < Dockerfile
