name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.8', '3.8', '3.8', '3.8']
        include:
          - python-version: '3.8'
            toxenv: py38
          - python-version: '3.8'
            toxenv: py38
          - python-version: '3.8'
            toxenv: py38
          - python-version: '3.8'
            toxenv: py38-dev
          - python-version: '3.8'
            toxenv: py3.8
          - python-version: '3.8'
            toxenv: docs
          - python-version: '3.8'
            toxenv: pep8
          - python-version: '3.8'
            toxenv: cover
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pbr tox tox-gh-actions
          pip install -r doc/requirements.txt .[test]
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pbr
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*
